apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  db_host: "prod-cloudladder-mysql-users.cbmq2qk2uqly.ap-northeast-2.rds.amazonaws.com"
  db_port: "3306"
  db_name: "users"
  db_user: "admin"