apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-frontend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-frontend
  template:
    metadata:
      labels:
        app: nodejs-frontend
    spec:
      containers:
        - name: nodejs-frontend
          image: 739306822356.dkr.ecr.ap-northeast-2.amazonaws.com/test:55721320cd6705ffa987cf9bd985f4fb10650fea
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: db_host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: db_port
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: db_name
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: db_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: db_password
          resources:
            requests:
              cpu: 300m
              memory: 500Mi
            limits:
              cpu: 400m
              memory: 600Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 3
            successThreshold: 2
            failureThreshold: 3
            periodSeconds: 10