apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nodejs-frontend
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nodejs-frontend
  template:
    metadata:
      labels:
        app: nodejs-frontend
    spec:
      containers:
        - name: nodejs-frontend
          image: 611155787285.dkr.ecr.ap-northeast-2.amazonaws.com/node_cloudladder:3a8dd63a69e67ff8cf11c985b12a25d7f8424761
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: db_host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: db_port
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: db_name
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: db_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: db_password
          resources:
            requests:
              cpu: 300m
              memory: 500Mi
            limits:
              cpu: 400m
              memory: 600Mi
#          readinessProbe:
#            httpGet:
#              path: /health
#              port: 3000
#            initialDelaySeconds: 10
#            timeoutSeconds: 3
#            successThreshold: 2
#            failureThreshold: 3
#            periodSeconds: 10
  strategy:
    blueGreen:
      activeService: nodejs-frontend-blue
      previewService: nodejs-frontend-green
      autoPromotionEnabled: true