apiVersion: v1
kind: Service
metadata:
  name: nodejs-frontend-green
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  selector:
    app: nodejs-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30082