apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
images:
- name: 611155787285.dkr.ecr.ap-northeast-2.amazonaws.com/node_cloudladder
  newName: 611155787285.dkr.ecr.ap-northeast-2.amazonaws.com/node_cloudladder
  newTag: 927e145a1d2cf8db0dfaaa124df7864d093056a1
