apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: 611155787285.dkr.ecr.ap-northeast-2.amazonaws.com/node_cloudladder
  newName: 611155787285.dkr.ecr.ap-northeast-2.amazonaws.com/node_cloudladder
  newTag: 005ac4056cc9029222e3a63637fe9e096c5dccb7

resources:
- ../../base
