apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization



resources:
- ../../base
- config.yaml

images:
- name: 611155787285.dkr.ecr.ap-northeast-2.amazonaws.com/node_cloudladder
  newName: 611155787285.dkr.ecr.ap-northeast-2.amazonaws.com/node_cloudladder
  newTag: 33b3ed8b4d7f3c97ac79752d8f0939dce438c448
