apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
images:
- name: 611155787285.dkr.ecr.ap-northeast-2.amazonaws.com/node_cloudladder
  newName: 611155787285.dkr.ecr.ap-northeast-2.amazonaws.com/node_cloudladder
  newTag: 36cc327aa32edea59d2545148b26b57917f8a3b8
